### ISSUE TITLE
Publish pure Python wheels under a separate PyPI name?

### ISSUE THREAD

**Issue by bwoodsend** [ariebovenberg/whenever#158]
I'm a big fan of Alpine/musl Linux so an extra 4 MBs of disk footprint plus all the security implications of a static/vendored runtime (both `libgcc` and Rust's runtime are in there) are a pretty high cost for Rust's *performance boost* in a library that wasn't anywhere close to being a bottleneck.

You do already have [an opt-out](https://whenever.readthedocs.io/en/latest/faq.html#how-can-i-use-the-pure-python-version) for the Rust stuff but it's not really sufficient – I can't put it in a `requirements.txt` nor the `dependencies` section of a `pyproject.toml`. Would you be willing to create a separate project on PyPI with only the pure Python wheels to make them more accessible?

**Comment by ariebovenberg** [comment]
Hi @bwoodsend, thanks for posting.

I'm certainly up for this if it makes things easier. I'd have to give this some thought to ensure it doesn't have any unforeseen drawbacks.

Regarding `requirements.txt`, you can do:

```
some-other-dependency==0.4
whenever==0.6.3
--no-binary whenever
```

and with `poetry`:

```
poetry config --local installer.no-binary whenever
```

(don't forget to set `WHENEVER_NO_BUILD_RUST_EXT=1` of course)

I understand it's less clean than an `pip install whenever-py`, but note that having multiple packages on pypi also comes with downsides (i.e. it takes the rust/pure-python choice away from downstream clients, and what happens if both are installed?)

**Comment by bwoodsend** [comment]
It occurs to me that if someone did end up with both in their dependency tree somehow, they would probably expect to be able to pass one instance of `whenever.Instant()` to some function from `whenever_py`. That makes me rather less keen on this change...

**Comment by ariebovenberg** [comment]
Agree with your last comment. After installation, there should _only one_ module named `whenever`, and it either uses rust or pure Python.

Here are some alternative approaches I can think of, but most have a downside:
- (current approach) provide a way to disable building extension from source distribution. Downside: a bit complicated to configure (`--no-binary` with `WHENEVER_NO_BUILD_EXT`)
- a `whenever-py` package that installs itself as `whenever`. Downside: upstream dependencies will have to make this decision, potentially silently override downstream dependencies.
- a dummy `whenever-py` package that _if installed_, tells `whenever` to import the pure-python code, not the rust extension. Downside: the large binary is still installed, taking up space. Also, more exotic platforms will not be supported.
- Making the rust extension opt-in. `pip install whenever` would install pure-python, `pip install whenever[rust]` would install the speedups. Downside: most users wouldn't realize they need to add `rust`, and it may erroneously encourage upstream dependencies to depend on it.

**Comment by ariebovenberg** [comment]
Regarding your particular case: does adding `--no-binary whenever` to `requirements.txt` not work for you? Or is it the fact that it feels a bit clunky compared to a separate package?

**Comment by bwoodsend** [comment]
The `requirements.txt` was more just an example. I pretty much exclusively create setuptools projects then add `whenever` to its dependencies.

**Comment by ariebovenberg** [comment]
Ah I see how the current way of choosing rust/python doesn't fall neatly in your setup.

I'm curious though: how would you configure something like `--index-url` if you'd need to?

I draw this comparison because this is *also* something only the downstream user (i.e. the one who pip/poetry/etc. installs) can decide.

It seems the consensus in Python packaging is that this type of decision (`no-binary` or `index-url`) _cannot_ be made by a package, and these would typically be configured in a dockerfile or deployment script

**Comment by bwoodsend** [comment]
> I'm curious though: how would you configure something like --index-url if you'd need to?

I've so far never needed to. I'd probably tell people to put it in the `pip.conf` although that's hardly any less work.

**Comment by ariebovenberg** [comment]
It seems there's no easier way to provide the pure-Python version that doesn't have other drawbacks.

@bwoodsend one more thing: the `_pywhenever.py` module is vendorable, if that helps (but this of course comes with other downsides).

I'll add an entry in the FAQ about this topic

**Comment by bwoodsend** [comment]
How about:

* `pip install whenever_py` installs `whenvever/*.py`
* `pip install whenever` installs `whenever/{rust stuff}` (maybe move into a private `_whenever_rust` package if it's easier) and declares a dependency on `whenever_py=={same version}`

Then:

* People still get the rust stuff by default
* If a package chooses to use `whenever_py`, the end consumer can override by installing `whenever`
* If a package chooses to use `whenever`, the old environment variable/`--no-binary` approach will still work

If that makes your head hurt then feel free to close this as unactionable. I don't want to make things worse.

**Comment by ariebovenberg** [comment]
Interesting suggestion 👀 . If it indeed gives the advantages you mention I'd definitely consider it.

The question is though: is it possible for two packages (i.e. `whenever` and `whenever-py`) to be installed to the same directory (i.e. `whenever`). My intuition says no, but I'd have to give it a try...

**Comment by ariebovenberg** [comment]
Just did a quick-n-dirty test: any modules with the same package name will result in uninstallation of the previous package. This makes sense to me: you could get weird package 'merges' otherwise 🤔 . 

However, an alternative could work:
- a PyPI package named `whenever` installs itself as `_whenever_rust`. It depends on `whenever-py` PyPI package.
- a PyPI package named `whenever-py` installs itself as `whenever`. Its `__init__.py` checks whether `_whenever_rust` is installed and uses it if available. Otherwise, it just uses the Python version.

This solution would maybe solve everything—if there isn't anything I'm missing 🤔.

Things to already think about:
- Will it be prohibitively unintuitive for other libraries to depend on `whenever-py` instead of `whenever`?
- Will it be too confusing that there two ways to use the pure-Python version? i.e. `pip install whenever-py` and `WHENEVER_NO_BUILD_RUST_EXT=1 pip install whenever --no-binary whenever`?

**Comment by ariebovenberg** [comment]
One disadvantage I can think of this solution: while typical users doing `pip install whenever` will get the expected result (the rust version of the library), users installing a package that _depends_ on `whenever-py` will have to explicitly opt-in to the rust version (by declaring `whenever` in their own `requirements.txt` or similar)

I can think of a few responses to this:
1. Don't recommend libraries to depend on `whenever-py`. People using a library that uses `whenever` should use the `--no-binary` option to disable the rust version. People can still _directly_ depend on `whenever-py` without problems.
2. Educate users about the fact that they may need to explicitly depend on `whenever` to get the speed boost (this is a hard sell)
3. Instruct library designers that they should have a `rust-speedups` extra, i.e. `foo` only installs `whenever-py` and `foo[rust-speedups]` would install `whenever`, not only `whenever-py`. Also a hard sell.

Option 1 is probably the most realistic, at the cost of having two different ways to do the same thing. Not sure if it'd be worth it 🤔

**Comment by bwoodsend** [comment]
> I suppose you'd need to instruct library developers to educate their users about whenever speedups (perhaps using 'extras'), if they opt for depending on whenever-py. Perhaps they can use "extras" like foo[rust-speedups]

I do maintain that this should be a minority. You really don't have to do much outside of `whenever` before the performance benefit of Rust is overshadowed by something else. Libraries should usually know if they fall into the *you won't notice it* camp.

```python
>>> whenever._EXTENSION_LOADED
False
>>> now = whenever.Instant.now()
>>> timeit.timeit(lambda: now.format_rfc3339(), number=1_000_000)
1.6375649879919365
# Some unrealistically minimal REST API style collateral code already costing more than the format_rfc3339()
>>> timeit.timeit(lambda: json.dumps({"time": now.format_rfc3339()}), number=1_000_000)
3.4939360100543126
```

I find the meaning of the word *confusing* varies depending on who your package attracts but I think this is odd but fairly explainable:

*Running `pip install whenever` will install the pure Python implementation (`whenever-py`) plus some speedups written in Rust. If you do not want or need the speedups, you can run `pip install whenever-py` instead. For packages that depend on `whenever`, prefer adding `whenever-py` to your dependencies instead of `whenever` but advise your downstream users that they may get a speedup by additionally installing `whenever`.*

The part I'm struggling with is to make the distinction between *whenever* the project and *whenever* the Python package. I'm hoping that the *prefer adding `whenever-py` to your dependencies* would remove the need to mention the `WHENEVER_NO_BUILD_RUST_EXT` switch.

**Comment by spacemanspiff2007** [comment]
@bwoodsend Out of curiosity - can you show what the output of timeit for the above example would be for the rust version on your machine?

---

Personally I don't understand why I should opt for something that is slower? If I read this as a library developer I'll always go with `whenever`. Why should I put additional burdens on the library users and make them additionally install something. Nobody has ever complained that something too fast. :wink:
And even if I decided to opt for the python version then I would have to provide additional packages like `my-lib[speedups]` because every thing else is too hard. Why would I make myself more work. 

As far as I understand from the first post the issue is a 4MB size increase which is nothing. 
If I can trade 4MB of space for 0.01% CPU time I will always do it.

I currently fail to see the benefit for the added complexity.

**Comment by bwoodsend** [comment]
> Out of curiosity - can you show what the output of timeit for the above example would be for the rust version on your machine?

Do bear in mind that the example is completely fabricated though...
```python
>>> timeit.timeit(lambda: json.dumps({"time": now.format_rfc3339()}), number=1_000_000)
3.4939360100543126
>>> timeit.timeit(lambda: now.format_rfc3339(), number=1_000_000)
1.6375649879919365
```

> As far as I understand from the first post the issue is a 4MB size increase which is nothing.
If I can trade 4MB of space for 0.01% CPU time I will always do it.

Well if that was the universal mindset then we wouldn't be having this discussion.

* I do a lot of packaging over ~300KB/s network rates so 4MB stings. I do not care about a performance boost that I cannot see.
* Lambda web services bill you almost exclusively based on space. For example, if I buy 1GB I can either have 1000 / 20 = 50 runners or 1000 / (20 + 4) = 41 runners so unless rust gives me an overall boost of > (50 - 41) / 50 = 18% (which it won't because handling HTTP requests costs way more than converting datetimes), then rust will actually slow the overall service down.
* And there's still the security aspect. Rust is statically linked meaning that CVEs (of which it produces [a fair number](https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=rust)) are *sticky*. For me to feel comfortable about having rust anywhere secure, someone would have to track that list in realtime for vulnerabilities, filter for those that end up in the rust binaries and again for those which are actually relevant, then bump the Rust toolchains and rerelease whenever one does come through and publish advisories telling everyone to upgrade `whenever`. I don't want to put that burden on myself or Arie so I'd rather make the *secure by default* route as practical as possible.

**Comment by ariebovenberg** [comment]
Happy to see a vibrant discussion here. While there's much to be said on whether to prefer the Rust or Python version, it's clear that we should keep giving the users a choice. The question is whether the method of choosing between them can be improved. 

I'm leaning towards keeping the current behavior, since:
- choosing between Rust and Python is something that should be up to the downstream user (i.e. somebody deploying an app, or running a script) and _not_ upstream libraries.
- People choosing the pure-Python version will probably have reasons for this decision, and are generally more familiar with customizing their installation (using `--no-binary`) than the average user.

In some utopic world, all Rust/C-extensions to Python would be optional and the packaging ecosystem would support it natively, like `pip install everything.txt --prefer-pure-python` and `pip install everything.txt --prefer-binary` or something.

**Comment by bwoodsend** [comment]
> I'm leaning towards keeping the current behavior

Fair enough. Let's call it a day then. Thanks for considering it anyway.

**Comment by ariebovenberg** [comment]
Well: _for now_ I'm not changing it, but I have a feeling may reconsider this in the future 🤔 and get more feedback from users.

**Comment by skorokithakis** [comment]
I'm not entirely current on how packaging works, but I do want to note one thing:

The only reason that I can see for someone to prefer Python over Rust is that they can't install/build the binary (for whatever reason). This means that, if the Rust package is installed, there's probably no reason to not default to that.

I was thinking something like:

* Release packages `whenever` (Rust) and `whenever-py` (Python).
* Both packages can be imported with `import whenever`.
* If both versions are found, the Rust version wins.

I'm not sure how the last step could be done, unless it's with some hacks specified above, but maybe someone knows. Maybe the solution is indeed to have a package be accessible as an alias, ie `_whenever_rust`, so if the Python version of `whenever` is imported with `import whenever`, it does:

```
try:
    from _whenever_rust import *
except:
    <normal module imports that will be exposed>
```

This way, the Python package will basically replace itself with the Rust package, if it's found.

Sorry if this was mentioned above, I didn't manage to follow the discussion completely.

**Comment by ariebovenberg** [comment]
Don't worry, I don't follow all my posts from months ago either 😅 

What you're proposing regarding two packages and the rust version "winning" is possible (it is in fact what the current code does!). The downside is you need to convince library designers (that depend on whenever) to:
- put `whenever-py` as a dependency, _not_ `whenever`. If they don't, then they actually _take away_ the choice from users of their library
- tell _their_ users that they need to install `whenever` to get datetime speedups

This is at odds with the fact that:
- _most_ people just want the rust version
- people generally don't follow detailed instructions like this
