### ISSUE TITLE
Support `float` in `Instant.from_timestamp()`

### ISSUE THREAD

**Issue by mihirsamdarshi** [ariebovenberg/whenever#159]
I was hoping it was possible to support `float`s in `from_timestamp`? 

I am working with tools that use `pendulum`, whose [`pendulum.DateTime.timestamp()` method returns a float](https://pendulum.eustace.io/docs/#attributes-and-properties). I am now trying to use those float values using `whenever`, since I appreciate the speed and strict typing.

I opened this issue because I couldn't find any relevant discussion why this wasn't already the case.

**Comment by ariebovenberg** [comment]
Hi @mihirsamdarshi, thanks for posting. Supporting `float` in `from_timestamp()` seems very reasonable 👍 , especially considering the common use case of migration from `datetime` and `pendulum`. I'll see if I can include this in the next release.

Note though that the `timestamp()` methods will continue to be `int` however, since:
1. `float` cannot support full nanosecond precision
1. other modern datetime libraries also do this

See the previous discussion here #63 . I'm fine with making the `from_timestamp()` allow float, since any precision loss has already occurred if the timestamp is already a float.

If you're looking for a workaround until the next release, try this:

```python
float_timestamp = pendulum_dt.now().timestamp()
Instant.from_timestamp_nanos(int(float_timestamp * 1_000_000_000))
```

**Comment by mihirsamdarshi** [comment]
Of course, my mistake not mentioning earlier that I had seen the discussion regarding not returning `float` values in `timestamp()` and that was perfectly cool with me

**Comment by ariebovenberg** [comment]
Version 0.6.5 is now out with the change 🚀
